# Generated by Django 5.1.1 on 2024-09-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_user',
            name='bg_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='bg_profile_picture'),
        ),
        migrations.AlterField(
            model_name='admin_user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='admin_user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='admin_user',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='admin_user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture'),
        ),
        migrations.AlterField(
            model_name='admin_user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
