# Generated by Django 5.1.1 on 2024-10-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_subject_teachers_alter_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teachers',
        ),
    ]
