# Generated by Django 5.1.1 on 2024-10-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_grade_level_studentuser_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='form',
            field=models.CharField(blank=True, choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four')], max_length=10, null=True),
        ),
    ]
