# Generated by Django 5.1.1 on 2024-10-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_subject_teachers_alter_subject_name'),
        ('user', '0004_alter_studentuser_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheruser',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='taught_by', to='subject.subject'),
        ),
    ]
