# Generated by Django 5.1.1 on 2024-10-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_parentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentuser',
            name='relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
